# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d798bdb471b2da24038540e498eff24f"
name = "cartpromo"
application_url = "https://phpstack-1272348-6664469.cloudwaysapps.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app-uninstalled"
  

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_discounts"

[auth]
redirect_urls = [ "https://phpstack-1272348-6664469.cloudwaysapps.com/api/auth" ]

[app_proxy]
url = "https://phpstack-1272348-6664469.cloudwaysapps.com/proxy"
subpath = "cartpromo"
prefix = "apps"


